[package]
name = "mrs-matrix"
authors = ["generic-user1"]
description = "A multiplatform Rust clone of cmatrix"
repository = "https://github.com/generic-user1/mrs-matrix"
documentation = "https://docs.rs/mrs-matrix/latest"
edition = "2021"
license = "MIT"
readme = "README.md"
keywords = ["matrix", "cmatrix", "multiplatform"]
categories = ["command-line-utilities", "games"]
version = "2.0.0"


[dependencies]
crossterm = "0.29.0"
coolor = { version = "1.1.0", features = ["crossterm"] }
rand = "0.10.2"
clap = { version = "4.6.6", features = ["derive"] }
